language: r
cache: packages
warnings_are_errors: false

repos:
  CRAN: https://cloud.r-project.org

r_binary_packages:
 - rgl
 - Rcpp
 - RcppEigen
 - RcppArmadillo
 - foreach
 - Matrix
 - MASS
 - car
 - rvcg
 - morpho
 - testthat
 
notifications:
  email:
    on_success: change
    on_failure: change


env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    - _R_CHECK_FORCE_SUGGESTS_: false
    - RGL_USE_NULL: true