language: r
cache: packages
warnings_are_errors: false

addons:
  apt:
    packages:
      - libpng-dev
      - libfreetype6-dev
      - libglu1-mesa-dev
      - libgl1-mesa-dev
      - libx11-dev
      - libxt-dev
      - x11proto-core-dev
      - autotools-dev
      
repos:
  CRAN: https://cloud.r-project.org

r_packages:
 - Rvcg
 - Morpho
 - rgl
 - Rcpp
 - RcppEigen
 - RcppArmadillo
 - foreach
 - Matrix
 - MASS
 - car
 - testthat

notifications:
  email:
    on_success: change
    on_failure: change


env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    - _R_CHECK_FORCE_SUGGESTS_: false
    - RGL_USE_NULL: true